/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import dao.Utilitario;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Exchange;
import model.MercadoBitcoin;
import model.DB;

/**
 *
 * @author lucas
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    DB db = new DB();
    ArrayList<Exchange> exchanges = new ArrayList<>();

    public TelaPrincipal() {
        initComponents();
        preencheComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jComboBoxExchange = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxMoeda = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelCompra = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelVenda = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelMaiorPreço = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelMenorPreco = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelVolume = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelUltimoValor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBoxExchange.setSelectedIndex(-1);
        jComboBoxExchange.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxExchangeItemStateChanged(evt);
            }
        });

        jLabel1.setText("Exchange:");

        jButton1.setText("Buscar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel2.setText("Moeda:");

        jComboBoxMoeda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMoedaItemStateChanged(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Preço de Compra:");

        jLabelCompra.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelCompra.setForeground(new java.awt.Color(0, 204, 0));
        jLabelCompra.setText("R$0.000,00");

        jLabel5.setText("Preço de Venda:");

        jLabelVenda.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelVenda.setForeground(new java.awt.Color(255, 0, 0));
        jLabelVenda.setText("R$0.000,00");

        jLabel4.setText("Maior Preço 24h:");

        jLabelMaiorPreço.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelMaiorPreço.setText("R$0.000,00");

        jLabel6.setText("Menor Preço 24h:");

        jLabelMenorPreco.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelMenorPreco.setText("R$0.000,00");

        jLabel7.setText("moedas negociadas nas últimas 24 horas");

        jLabelVolume.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelVolume.setText("0.000,00");

        jLabel8.setText("Ultimo Valor Negociado:");

        jLabelUltimoValor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelUltimoValor.setText("R$0.000,00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMaiorPreço)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMenorPreco))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabelVolume)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelVenda)))
                .addGap(0, 32, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUltimoValor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelCompra)
                    .addComponent(jLabel5)
                    .addComponent(jLabelVenda))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelMaiorPreço)
                    .addComponent(jLabel6)
                    .addComponent(jLabelMenorPreco))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelVolume))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelUltimoValor))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxMoeda, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxExchange, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(287, 287, 287))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxExchange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxMoeda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(695, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxExchangeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxExchangeItemStateChanged
        int posicao = jComboBoxExchange.getSelectedIndex();
        System.out.println(posicao);
        //System.out.println(posicao);
        int qtdMoedas = exchanges.get(posicao).getMoedas().size();
        jComboBoxMoeda.removeAllItems();
        for (int i = 0; i < qtdMoedas; i++) {

            jComboBoxMoeda.addItem(exchanges.get(posicao).getMoedas().get(i));
        }
        
        String texto = "R$0.000,00";
        jLabelCompra.setText(texto);
        jLabelMaiorPreço.setText(texto);
        jLabelMenorPreco.setText(texto);
        jLabelUltimoValor.setText(texto);
        jLabelVenda.setText(texto);
        jLabelVolume.setText("0");
    }//GEN-LAST:event_jComboBoxExchangeItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        DecimalFormat format = new DecimalFormat("R$#,##0.00");

        int posicaoExchange = jComboBoxExchange.getSelectedIndex();

        String moeda = jComboBoxMoeda.getSelectedItem().toString();
        String uri = exchanges.get(posicaoExchange).getURI() + moeda + exchanges.get(posicaoExchange).getMetodo();

        Utilitario util = new Utilitario();
        String retorno = util.sendGet(uri, "GET");
        if (retorno != null) {
            GsonBuilder gson = new GsonBuilder();
            Gson pegador = gson.create();
            MercadoBitcoin t = pegador.fromJson(retorno, MercadoBitcoin.class);
            //System.out.println(retorno);
            System.out.println(t.getTicker());
            jLabelCompra.setText(format.format(t.getTicker().getBuy()));
            jLabelVenda.setText(format.format(t.getTicker().getSell()));
            jLabelMaiorPreço.setText(format.format(t.getTicker().getHigh()));
            jLabelMenorPreco.setText(format.format(t.getTicker().getLow()));
            jLabelVolume.setText(String.valueOf(t.getTicker().getVol()));
            jLabelUltimoValor.setText(format.format(t.getTicker().getLast()));
        } else {
            System.out.println("erro ao executar http");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jComboBoxMoedaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMoedaItemStateChanged
        String texto = "R$0.000,00";
        jLabelCompra.setText(texto);
        jLabelMaiorPreço.setText(texto);
        jLabelMenorPreco.setText(texto);
        jLabelUltimoValor.setText(texto);
        jLabelVenda.setText(texto);
        jLabelVolume.setText("0");
    }//GEN-LAST:event_jComboBoxMoedaItemStateChanged

    public void preencheComboBox() {

        //jComboBoxExchange.setSelectedIndex(-1);
        exchanges = db.getAllExchange();
        int tamanho = exchanges.size();
        for (int i = 0; i < tamanho; i++) {
            jComboBoxExchange.addItem(exchanges.get(i).getNome());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxExchange;
    private javax.swing.JComboBox<String> jComboBoxMoeda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCompra;
    private javax.swing.JLabel jLabelMaiorPreço;
    private javax.swing.JLabel jLabelMenorPreco;
    private javax.swing.JLabel jLabelUltimoValor;
    private javax.swing.JLabel jLabelVenda;
    private javax.swing.JLabel jLabelVolume;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
